In [ ]:
#reverse a string
str = "pwslills"
str[::-1]

'sllilswp'

In [ ]:
#counting vowels in a string
sentence = input("enter sentence")
string = sentence.lower()
vowels = "aeiou"
count = 0
for i in string:
    if i in vowels:
        count += 1
print(count)

enter sentence  aaron
3

In [ ]:
sentence = input("enter sentence")
string = sentence.lower()
print(string)
count = 0
list1 = ["a","e","i","o","u"]
for char in string:
    if char in list1:
        count = count+1
print("number of vowels in sentence is  " , count)

enter sentence   aeiou
   aeiou
number of vowels in sentence is   5

In [ ]:
#Write code to check if given string is  palindrome or not
str = input("enter string:  ")
if str == str[::-1]:
    print("palindrome")
else:
    print("not palindrome")

enter string:  madam
palindrome

In [ ]:
#Write code to check if two given strings are anagram of eachh other.
str1 = input("enter first string:  ")
str2 = input("enter second string:  ")
if sorted(str1) == sorted(str2):
    print("anagram")
else:
    print("not anagram")

enter first string:  silent
enter second string:  listen
anagram

In [ ]:
#Write code to find all occurence of a given substring within another string.

In [ ]:
# Write a code to perform basic string compression using the counts of repeated character

In [ ]:
#Write a code to determine if a string has all unique character
def is_unique_character(s):
    sorted(s)
    for i in range(len(s)-1):
      if s[i]==s[i+1]:                 #checks whether the string contains duplicate
        return False
    return True

s=input().lower()
if is_unique_character(s):
    print("the string",s,"has all unique characters")
else:
    print("the string",s,"has duplicate characters")

anro
the string anro has all unique characters

In [ ]:
#write a code to convert given string to upper case or lower case
str = input("enter string:  ")
print(str.upper())
print(str.lower())

enter string:  aaron
AARON
aaron

In [ ]:
#write a code to count number of words in a string
str = "aaron"
len(str)

5

In [ ]:
from posixpath import join
 #Write a code to concatenate two strings without using the + operator
str1 = "pw"
str2 = "skills"
print("".join([str1,str2]))

pwskills

In [ ]:
#Write a code to remove all occurrences of a specific element from a list
list1 = [1, 2.2, 3+2j, "pwskills", True, "pwskills", "pwskills"]
while "pwskills" in list1:
    list1.remove("pwskills")
print(list1)

[1, 2.2, (3+2j), True]

In [ ]:
#Implement a code to find the second largest number in a given list of integers.
lit1 = [1,2,3,4,5,6,7,8,9]
lit1.sort()
print(lit1[-2])

8

In [ ]:
#Create a code to count the occurrences of each element in a list and return a dictionary with elements as keys and their counts as values.
# Create a list
my_list = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]

# Create an empty dictionary to store the counts
counts = {}

# Iterate over the list and count the occurrences of each element
for element in my_list:
    if element in counts:
        counts[element] += 1
    else:
        counts[element] = 1

# Print the dictionary
print(counts)

{1: 1, 2: 2, 3: 3, 4: 4}

In [ ]:
#Write a code to reverse a list in-place without using any built-in reverse functions
# Reversing a list using slicing technique
def Reverse(lst):
   new_lst = lst[::-1]
   return new_lst


lst = [10, 11, 12, 13, 14, 15]
print(Reverse(lst))

[15, 14, 13, 12, 11, 10]

In [ ]:
#Implement a code to find and remove duplicates from a list while preserving the original order of elements
my_list = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
new_list = list(dict.fromkeys(my_list))
print(new_list)

[1, 2, 3, 4]

In [ ]:
#Create a code to check if a given list is sorted (either in ascending or descending order or not.
def is_sorted(lst):
  return lst == sorted(lst) or lst == sorted(lst, reverse=True)

# Example usage
lst1 = [1, 2, 3, 4, 5]
lst2 = [5, 4, 3, 2, 1]
lst3 = [1, 3, 2, 4, 5]

print(is_sorted(lst1))  # Output: True
print(is_sorted(lst2))  # Output: True
print(is_sorted(lst3))  # Output: False

True
True
False

In [ ]:
#Write a code to merge two sorted lists into a single sorted list.
list1 = [1,3,5]
list2 = [2,4,6]
merged_list = sorted(list1 + list2)
print(merged_list)

[1, 2, 3, 4, 5, 6]

In [ ]:
 #Implement a code to find the intersection of two given lists.
 # Define the two lists
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

# Find the intersection using set intersection
intersection = list(set(list1) & set(list2))

# Print the intersection
print(intersection)

[3, 4, 5]

In [ ]:
#Create a code to find the union of two lists without duplicates.
# Define the two lists
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

# Find the union using set union
union = list(set(list1) | set(list2))

# Print the union
print(union)

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
# Write a code to shuffle a given list randomly without using any built-in shuffle functions.

In [ ]:
# Write a code that takes two tuples as input and returns a new tuple containing elements that are common to both input tuples.
def common_elements(tuple1, tuple2):
  return tuple(set(tuple1) & set(tuple2))

# Example usage
tuple1 = (1, 2, 3, 4, 5)
tuple2 = (3, 4, 5, 6, 7)
common_tuple = common_elements(tuple1, tuple2)
print(common_tuple)

(3, 4, 5)

In [ ]:
#Create a code that prompts the user to enter two sets of integers separated by commas. Then, print the intersection of these two sets

In [ ]:
#Write a code to concatenate two tuples. The function should take two tuples as input and return a new tuple containing elements from both input tuples
tuple1 = (1,2,3,4,5)
tuple2 = (4,5,6,7,8)
print(tuple1 + tuple2)

(1, 2, 3, 4, 5, 4, 5, 6, 7, 8)

In [1]:
#Develop a code that prompts the user to input two sets of strings. then, print the elements that are present in the first set but not in the second set.
# Get input from the user for the first set
set1_str = input("Enter the first set of strings separated by commas: ")
set1 = set(set1_str.split(","))

# Get input from the user for the second set
set2_str = input("Enter the second set of strings separated by commas: ")
set2 = set(set2_str.split(","))

# Find the difference between the two sets
difference = set1 - set2

# Print the elements present in the first set but not in the second set
print(difference)

Enter the first set of strings separated by commas: apple, banana, mango, orange, kiwi
Enter the second set of strings separated by commas: orange,kiwi,grapes,pineapple
{' orange', ' banana', 'apple', ' kiwi', ' mango'}

In [2]:
#create a code that takes a tuple and two integers as input. the function should return a new tuple containing elements from the original tuple within the specified range of indices
def tuple_slice(tup, start, end):
    return tup[start:end]

# Example usage
my_tuple = (1, 2, 3, 4, 5)
start_index = 1
end_index = 4
sliced_tuple = tuple_slice(my_tuple, start_index, end_index)
print(sliced_tuple)

(2, 3, 4)

In [3]:
#write a code that prompts the user to input two sets of character. then, print the union of these two sets.
# Get input from the user for the first set
set1_str = input("Enter the first set of characters separated by commas: ")
set1 = set(set1_str.split(","))

# Get input from the user for the second set
set2_str = input("Enter the second set of characters separated by commas: ")
set2 = set(set2_str.split(","))

# Find the union of the two sets
union = set1 | set2

# Print the union
print(union)

Enter the first set of characters separated by commas: apple, banana, mango, orange ,kiwi
Enter the second set of characters separated by commas: orange, kiwi, grapes, avacoda
{'orange', ' avacoda', ' banana', 'apple', ' grapes', ' kiwi', ' mango', ' orange ', 'kiwi'}

In [4]:
#develop a code that takes a tuole of integers as input. the function should return the maximum and minimum values from the tuple using tuple unpacking.
def find_max_min(numbers):
  min_val = min(numbers)
  max_val = max(numbers)
  return min_val, max_val

# Example usage
numbers = (1, 2, 3, 4, 5)
min_num, max_num = find_max_min(numbers)
print(f"Minimum: {min_num}, Maximum: {max_num}")

Minimum: 1, Maximum: 5

In [5]:
#create a code that defines two sets of integers. then, print the union,and difference of these two sets
# Define the two sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}

# Calculate the union of the two sets
union_set = set1 | set2

# Calculate the difference of the two sets (set1 - set2)
difference_set = set1 - set2

# Print the union and difference
print("Union:", union_set)
print("Difference (set1 - set2):", difference_set)

Union: {1, 2, 3, 4, 5, 6, 7}
Difference (set1 - set2): {1, 2}

In [7]:
#write a code that takes a tuple and an element as input. the function should return the count of occurances of the given element in the tuple
def count_occurrences(tup, element):
  return tup.count(element)

# Example usage
my_tuple = (1, 2, 2, 3, 3, 3)
element = 3
count = count_occurrences(my_tuple, element)
print(count)  # Output: 3

3

In [8]:
#develop a code that prompts the user to input two sets of strings. then, print the symmetric difference of two sets.
# Get input from the user for the first set
set1_str = input("Enter the first set of strings separated by commas: ")
set1 = set(set1_str.split(","))

# Get input from the user for the second set
set2_str = input("Enter the second set of strings separated by commas: ")
set2 = set(set2_str.split(","))

# Calculate the symmetric difference of the two sets
symmetric_difference = set1 ^ set2

# Print the symmetric difference
print(symmetric_difference)

Enter the first set of strings separated by commas: apple, orange, banana,kiwi
Enter the second set of strings separated by commas: banana, kiwi,grapes, pineappple
{' orange', ' banana', 'grapes', 'apple', ' pineappple', ' kiwi', 'banana', 'kiwi'}

In [9]:
#write a code that takes a list of words as input and returns a dictionary where the keys are unique words and the values are the frequencies of those words in the input list
def word_frequencies(words):
  """
  This function takes a list of words and returns a dictionary with word frequencies.
  """
  frequency = {}
  for word in words:
    frequency[word] = frequency.get(word, 0) + 1
  return frequency

# Example usage
words = ["apple", "banana", "apple", "cherry", "banana", "apple"]
result = word_frequencies(words)
print(result)  # Output: {'apple': 3, 'banana': 2, 'cherry': 1}

{'apple': 3, 'banana': 2, 'cherry': 1}

In [10]:
#write a code that takes two dictionaries as input and merge them into single dictionary. if there are common keys,the value should be added together
def merge_dicts(dict1, dict2):
  merged = dict1.copy()
  for key, value in dict2.items():
    if key in merged:
      merged[key] += value
    else:
      merged[key] = value
  return merged

# Example usage
dict1 = {'a': 1, 'b': 2, 'c': 3}
dict2 = {'b': 3, 'c': 4, 'd': 5}
merged_dict = merge_dicts(dict1, dict2)
print(merged_dict)  # Output: {'a': 1, 'b': 5, 'c': 7, 'd': 5}

{'a': 1, 'b': 5, 'c': 7, 'd': 5}

In [11]:
#write a code to access a value in a nested dictionary. the function should take the dictionary and a list of keys as input and return the corresponding value. if any keys do not exist in the dictionary,the function should return none.
def get_nested_value(nested_dict, key_list):
  """
  Accesses a value in a nested dictionary using a list of keys.

  Args:
    nested_dict: The nested dictionary.
    key_list: A list of keys to access the value.

  Returns:
    The corresponding value if all keys exist, otherwise None.
  """
  current_level = nested_dict
  for key in key_list:
    if key not in current_level:
      return None
    current_level = current_level[key]
  return current_level

 # Example usage
nested_dict = {"a": {"b": {"c": 10}}}
key_list = ["a", "b", "c"]
value = get_nested_value(nested_dict, key_list)
print(value)  # Output: 10

key_list = ["a", "b", "d"]
value = get_nested_value(nested_dict, key_list)
print(value)  #output: none

10
None

In [12]:
#write a code that takes a dictionary as input and returns a sorteed version of it based on the values. you can choose whether to sort in ascending or descending order
def sort_dictionary_by_values(input_dict, ascending=True):
  """
  Sorts a dictionary by its values.

  Args:
    input_dict: The dictionary to sort.
    ascending: Whether to sort in ascending order (default) or descending order.

  Returns:
    A new dictionary sorted by values.
  """
  sorted_items = sorted(input_dict.items(), key=lambda item: item[1], reverse=not ascending)
  return dict(sorted_items)

# Example usage
my_dict = {'a': 3, 'b': 1, 'c': 2}
sorted_dict_asc = sort_dictionary_by_values(my_dict)
print(sorted_dict_asc)  # Output: {'b': 1, 'c': 2, 'a': 3}

sorted_dict_desc = sort_dictionary_by_values(my_dict, ascending=False)
print(sorted_dict_desc)  # Output: {'a': 3, 'c': 2, 'b': 1}

{'b': 1, 'c': 2, 'a': 3}
{'a': 3, 'c': 2, 'b': 1}

In [13]:
#write a code that inverts a dictionary , swaapping keys and values. ensure that the inverted dictionary correctly handles cases where multiple keys have the same values by storing thr keys as a list in the inverted dictionary
from collections import defaultdict

def invert_dictionary(input_dict):
  """
  Inverts a dictionary, swapping keys and values.

  Args:
    input_dict: The dictionary to invert.

  Returns:
    A new dictionary with values as keys and keys as values (in a list if
    multiple keys have the same value).
  """
  inverted_dict = defaultdict(list)
  for key, value in input_dict.items():
    inverted_dict[value].append(key)
  return dict(inverted_dict)

# Example usage
my_dict = {'a': 1, 'b': 2, 'c': 1}
inverted_dict = invert_dictionary(my_dict)
print(inverted_dict)  # Output: {1: ['a', 'c'], 2: ['b']}

{1: ['a', 'c'], 2: ['b']}